# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release
on:
  push:
    branches:
      - main
concurrency: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GOOGLEWORKSPACE_BOT_TOKEN }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Test
        run: |
          npm ci
          npm test
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            semantic-release-interval
            @semantic-release/release-notes-generator
            @semantic-release/git
            @semantic-release/github
            @semantic-release/npm
            conventional-changelog-conventionalcommits
        env:
          GH_TOKEN: ${{ secrets.GOOGLEWORKSPACE_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_WOMBAT_TOKEN }}
